
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


--
-- Štruktúra tabuľky pre tabuľku `sendera_report`
--

CREATE TABLE IF NOT EXISTS `sendera_report` (
  `a_line` varchar(60) DEFAULT NULL,
  `b_line` varchar(60) DEFAULT NULL,
  `c_line` varchar(60) DEFAULT NULL,
  `d_line` varchar(60) DEFAULT NULL,
  `e_line` varchar(60) DEFAULT NULL,
  `f_line` varchar(60) DEFAULT NULL,
  `g_line` varchar(60) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
